package com.dao;

import com.bean.Checking;

public interface CheckingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    int insert(Checking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checking
     *
     * @mbggenerated
     */
    int insertSelective(Checking record);
}