package com.dao;

import com.bean.Weblog;

public interface WeblogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    int insert(Weblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    int insertSelective(Weblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    Weblog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Weblog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Weblog record);
}