package com.bean;

import java.util.Date;

public class Email {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.proto
     *
     * @mbggenerated
     */
    private String proto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.sip
     *
     * @mbggenerated
     */
    private String sip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.sport
     *
     * @mbggenerated
     */
    private Integer sport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.dip
     *
     * @mbggenerated
     */
    private String dip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.dport
     *
     * @mbggenerated
     */
    private Integer dport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.from
     *
     * @mbggenerated
     */
    private String from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.to
     *
     * @mbggenerated
     */
    private String to;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column email.istype
     *
     * @mbggenerated
     */
    private String istype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated
     */
    public Email(Integer id, Date time, String proto, String sip, Integer sport, String dip, Integer dport, String from, String to, String subject, String istype) {
        this.id = id;
        this.time = time;
        this.proto = proto;
        this.sip = sip;
        this.sport = sport;
        this.dip = dip;
        this.dport = dport;
        this.from = from;
        this.to = to;
        this.subject = subject;
        this.istype = istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table email
     *
     * @mbggenerated
     */
    public Email() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.id
     *
     * @return the value of email.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.id
     *
     * @param id the value for email.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.time
     *
     * @return the value of email.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.time
     *
     * @param time the value for email.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.proto
     *
     * @return the value of email.proto
     *
     * @mbggenerated
     */
    public String getProto() {
        return proto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.proto
     *
     * @param proto the value for email.proto
     *
     * @mbggenerated
     */
    public void setProto(String proto) {
        this.proto = proto == null ? null : proto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.sip
     *
     * @return the value of email.sip
     *
     * @mbggenerated
     */
    public String getSip() {
        return sip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.sip
     *
     * @param sip the value for email.sip
     *
     * @mbggenerated
     */
    public void setSip(String sip) {
        this.sip = sip == null ? null : sip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.sport
     *
     * @return the value of email.sport
     *
     * @mbggenerated
     */
    public Integer getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.sport
     *
     * @param sport the value for email.sport
     *
     * @mbggenerated
     */
    public void setSport(Integer sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.dip
     *
     * @return the value of email.dip
     *
     * @mbggenerated
     */
    public String getDip() {
        return dip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.dip
     *
     * @param dip the value for email.dip
     *
     * @mbggenerated
     */
    public void setDip(String dip) {
        this.dip = dip == null ? null : dip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.dport
     *
     * @return the value of email.dport
     *
     * @mbggenerated
     */
    public Integer getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.dport
     *
     * @param dport the value for email.dport
     *
     * @mbggenerated
     */
    public void setDport(Integer dport) {
        this.dport = dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.from
     *
     * @return the value of email.from
     *
     * @mbggenerated
     */
    public String getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.from
     *
     * @param from the value for email.from
     *
     * @mbggenerated
     */
    public void setFrom(String from) {
        this.from = from == null ? null : from.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.to
     *
     * @return the value of email.to
     *
     * @mbggenerated
     */
    public String getTo() {
        return to;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.to
     *
     * @param to the value for email.to
     *
     * @mbggenerated
     */
    public void setTo(String to) {
        this.to = to == null ? null : to.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.subject
     *
     * @return the value of email.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.subject
     *
     * @param subject the value for email.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column email.istype
     *
     * @return the value of email.istype
     *
     * @mbggenerated
     */
    public String getIstype() {
        return istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column email.istype
     *
     * @param istype the value for email.istype
     *
     * @mbggenerated
     */
    public void setIstype(String istype) {
        this.istype = istype == null ? null : istype.trim();
    }
}