package com.bean;

import java.util.Date;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.proto
     *
     * @mbggenerated
     */
    private String proto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.dip
     *
     * @mbggenerated
     */
    private String dip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.dport
     *
     * @mbggenerated
     */
    private Integer dport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.sip
     *
     * @mbggenerated
     */
    private String sip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.sport
     *
     * @mbggenerated
     */
    private Integer sport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.istype
     *
     * @mbggenerated
     */
    private String istype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    public Login(Integer id, String proto, String dip, Integer dport, String sip, Integer sport, String state, Date time, String user, String istype) {
        this.id = id;
        this.proto = proto;
        this.dip = dip;
        this.dport = dport;
        this.sip = sip;
        this.sport = sport;
        this.state = state;
        this.time = time;
        this.user = user;
        this.istype = istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login
     *
     * @mbggenerated
     */
    public Login() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.proto
     *
     * @return the value of login.proto
     *
     * @mbggenerated
     */
    public String getProto() {
        return proto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.proto
     *
     * @param proto the value for login.proto
     *
     * @mbggenerated
     */
    public void setProto(String proto) {
        this.proto = proto == null ? null : proto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.dip
     *
     * @return the value of login.dip
     *
     * @mbggenerated
     */
    public String getDip() {
        return dip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.dip
     *
     * @param dip the value for login.dip
     *
     * @mbggenerated
     */
    public void setDip(String dip) {
        this.dip = dip == null ? null : dip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.dport
     *
     * @return the value of login.dport
     *
     * @mbggenerated
     */
    public Integer getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.dport
     *
     * @param dport the value for login.dport
     *
     * @mbggenerated
     */
    public void setDport(Integer dport) {
        this.dport = dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.sip
     *
     * @return the value of login.sip
     *
     * @mbggenerated
     */
    public String getSip() {
        return sip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.sip
     *
     * @param sip the value for login.sip
     *
     * @mbggenerated
     */
    public void setSip(String sip) {
        this.sip = sip == null ? null : sip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.sport
     *
     * @return the value of login.sport
     *
     * @mbggenerated
     */
    public Integer getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.sport
     *
     * @param sport the value for login.sport
     *
     * @mbggenerated
     */
    public void setSport(Integer sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.state
     *
     * @return the value of login.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.state
     *
     * @param state the value for login.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.time
     *
     * @return the value of login.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.time
     *
     * @param time the value for login.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user
     *
     * @return the value of login.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user
     *
     * @param user the value for login.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.istype
     *
     * @return the value of login.istype
     *
     * @mbggenerated
     */
    public String getIstype() {
        return istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.istype
     *
     * @param istype the value for login.istype
     *
     * @mbggenerated
     */
    public void setIstype(String istype) {
        this.istype = istype == null ? null : istype.trim();
    }
}