package com.bean;

import java.util.Date;

public class Tcplog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.stime
     *
     * @mbggenerated
     */
    private Date stime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.dtime
     *
     * @mbggenerated
     */
    private Date dtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.proto
     *
     * @mbggenerated
     */
    private String proto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.dip
     *
     * @mbggenerated
     */
    private String dip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.dport
     *
     * @mbggenerated
     */
    private Integer dport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.sip
     *
     * @mbggenerated
     */
    private String sip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.sport
     *
     * @mbggenerated
     */
    private Integer sport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.uplink_length
     *
     * @mbggenerated
     */
    private Integer uplinkLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.downlink_length
     *
     * @mbggenerated
     */
    private Integer downlinkLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tcplog.istype
     *
     * @mbggenerated
     */
    private String istype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcplog
     *
     * @mbggenerated
     */
    public Tcplog(Integer id, Date stime, Date dtime, String proto, String dip, Integer dport, String sip, Integer sport, Integer uplinkLength, Integer downlinkLength, String istype) {
        this.id = id;
        this.stime = stime;
        this.dtime = dtime;
        this.proto = proto;
        this.dip = dip;
        this.dport = dport;
        this.sip = sip;
        this.sport = sport;
        this.uplinkLength = uplinkLength;
        this.downlinkLength = downlinkLength;
        this.istype = istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tcplog
     *
     * @mbggenerated
     */
    public Tcplog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.id
     *
     * @return the value of tcplog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.id
     *
     * @param id the value for tcplog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.stime
     *
     * @return the value of tcplog.stime
     *
     * @mbggenerated
     */
    public Date getStime() {
        return stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.stime
     *
     * @param stime the value for tcplog.stime
     *
     * @mbggenerated
     */
    public void setStime(Date stime) {
        this.stime = stime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.dtime
     *
     * @return the value of tcplog.dtime
     *
     * @mbggenerated
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.dtime
     *
     * @param dtime the value for tcplog.dtime
     *
     * @mbggenerated
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.proto
     *
     * @return the value of tcplog.proto
     *
     * @mbggenerated
     */
    public String getProto() {
        return proto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.proto
     *
     * @param proto the value for tcplog.proto
     *
     * @mbggenerated
     */
    public void setProto(String proto) {
        this.proto = proto == null ? null : proto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.dip
     *
     * @return the value of tcplog.dip
     *
     * @mbggenerated
     */
    public String getDip() {
        return dip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.dip
     *
     * @param dip the value for tcplog.dip
     *
     * @mbggenerated
     */
    public void setDip(String dip) {
        this.dip = dip == null ? null : dip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.dport
     *
     * @return the value of tcplog.dport
     *
     * @mbggenerated
     */
    public Integer getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.dport
     *
     * @param dport the value for tcplog.dport
     *
     * @mbggenerated
     */
    public void setDport(Integer dport) {
        this.dport = dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.sip
     *
     * @return the value of tcplog.sip
     *
     * @mbggenerated
     */
    public String getSip() {
        return sip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.sip
     *
     * @param sip the value for tcplog.sip
     *
     * @mbggenerated
     */
    public void setSip(String sip) {
        this.sip = sip == null ? null : sip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.sport
     *
     * @return the value of tcplog.sport
     *
     * @mbggenerated
     */
    public Integer getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.sport
     *
     * @param sport the value for tcplog.sport
     *
     * @mbggenerated
     */
    public void setSport(Integer sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.uplink_length
     *
     * @return the value of tcplog.uplink_length
     *
     * @mbggenerated
     */
    public Integer getUplinkLength() {
        return uplinkLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.uplink_length
     *
     * @param uplinkLength the value for tcplog.uplink_length
     *
     * @mbggenerated
     */
    public void setUplinkLength(Integer uplinkLength) {
        this.uplinkLength = uplinkLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.downlink_length
     *
     * @return the value of tcplog.downlink_length
     *
     * @mbggenerated
     */
    public Integer getDownlinkLength() {
        return downlinkLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.downlink_length
     *
     * @param downlinkLength the value for tcplog.downlink_length
     *
     * @mbggenerated
     */
    public void setDownlinkLength(Integer downlinkLength) {
        this.downlinkLength = downlinkLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tcplog.istype
     *
     * @return the value of tcplog.istype
     *
     * @mbggenerated
     */
    public String getIstype() {
        return istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tcplog.istype
     *
     * @param istype the value for tcplog.istype
     *
     * @mbggenerated
     */
    public void setIstype(String istype) {
        this.istype = istype == null ? null : istype.trim();
    }
}