package com.bean;

import java.util.Date;

public class Weblog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.sip
     *
     * @mbggenerated
     */
    private String sip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.sport
     *
     * @mbggenerated
     */
    private Integer sport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.dip
     *
     * @mbggenerated
     */
    private String dip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.dport
     *
     * @mbggenerated
     */
    private Integer dport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.host
     *
     * @mbggenerated
     */
    private String host;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column weblog.istype
     *
     * @mbggenerated
     */
    private String istype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    public Weblog(Integer id, Date time, String sip, Integer sport, String dip, Integer dport, String host, String istype) {
        this.id = id;
        this.time = time;
        this.sip = sip;
        this.sport = sport;
        this.dip = dip;
        this.dport = dport;
        this.host = host;
        this.istype = istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table weblog
     *
     * @mbggenerated
     */
    public Weblog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.id
     *
     * @return the value of weblog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.id
     *
     * @param id the value for weblog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.time
     *
     * @return the value of weblog.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.time
     *
     * @param time the value for weblog.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.sip
     *
     * @return the value of weblog.sip
     *
     * @mbggenerated
     */
    public String getSip() {
        return sip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.sip
     *
     * @param sip the value for weblog.sip
     *
     * @mbggenerated
     */
    public void setSip(String sip) {
        this.sip = sip == null ? null : sip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.sport
     *
     * @return the value of weblog.sport
     *
     * @mbggenerated
     */
    public Integer getSport() {
        return sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.sport
     *
     * @param sport the value for weblog.sport
     *
     * @mbggenerated
     */
    public void setSport(Integer sport) {
        this.sport = sport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.dip
     *
     * @return the value of weblog.dip
     *
     * @mbggenerated
     */
    public String getDip() {
        return dip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.dip
     *
     * @param dip the value for weblog.dip
     *
     * @mbggenerated
     */
    public void setDip(String dip) {
        this.dip = dip == null ? null : dip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.dport
     *
     * @return the value of weblog.dport
     *
     * @mbggenerated
     */
    public Integer getDport() {
        return dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.dport
     *
     * @param dport the value for weblog.dport
     *
     * @mbggenerated
     */
    public void setDport(Integer dport) {
        this.dport = dport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.host
     *
     * @return the value of weblog.host
     *
     * @mbggenerated
     */
    public String getHost() {
        return host;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.host
     *
     * @param host the value for weblog.host
     *
     * @mbggenerated
     */
    public void setHost(String host) {
        this.host = host == null ? null : host.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column weblog.istype
     *
     * @return the value of weblog.istype
     *
     * @mbggenerated
     */
    public String getIstype() {
        return istype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column weblog.istype
     *
     * @param istype the value for weblog.istype
     *
     * @mbggenerated
     */
    public void setIstype(String istype) {
        this.istype = istype == null ? null : istype.trim();
    }
}